### ISSUE TITLE
🔮[RFC #0010]:  Design Draft for OpenIM Configuration Discussion

### ISSUE THREAD

**Issue by cubxxw** [openimsdk/open-im-server#2157]
# Design Draft for OpenIM Configuration Discussion

## Meta
- Name: OpenIM Scalable and Maintainable Application Design Guide
- Start Date: 2024-04-01
- Author(s): @cubxxw 
- Status: Draft
- RFC Pull Request: (leave blank)
- OpenIMSDK Pull Request: (leave blank)
- OpenIMSDK Issue: (leave blank)
- Supersedes: N/A

## 📇Topics

- Summary
- Definitions
- Motivation
- What it is
- How it Works
- Migration
- Drawbacks
- Alternatives
- Prior Art
- Unresolved Questions
- Spec. Changes (OPTIONAL)
- History

## Summary

This document proposes a comprehensive guide for designing a production-ready, scalable, and maintainable application that is compatible with Kubernetes, openim-docker, and OpenIM source code. It delves into the intricacies of middleware partitioning, sensitive configuration handling, and presents solutions to configuration complexity.

## Definitions

- **Middleware Partitioning**: The process of separating application configuration into distinct sections to enhance flexibility and manageability.
- **Sensitive Configuration**: Configuration details that include sensitive information such as passwords and encryption keys.
- **Kubernetes Secrets**: A Kubernetes object used to store sensitive information, such as passwords, OAuth tokens, and ssh keys.
- **HashiCorp Vault**: A tool for secrets management, encrypting sensitive data, and controlling access to tokens, passwords, certificates, API keys, and other secrets in modern computing.
- **KMS (Key Management Service)**: A service that allows users to manage encryption keys for their data.

## Motivation

The primary motivation behind this guide is to address the challenges of designing a scalable, maintainable, and flexible application architecture. It seeks to provide clear strategies for handling configuration complexity, middleware partitioning, and sensitive information management, thereby ensuring operational efficiency and security.

## What it is

This guide introduces a design philosophy that encompasses the partitioning of middleware, the separation of application versus environment configurations, and the secure handling of sensitive data. It advocates for the automation of configuration management through tools like Kubernetes, Kustomize/Helm, and introduces a new deployment tool, imops, to streamline deployment processes.

## How it Works

The design leverages Kubernetes for orchestrating containerized applications, utilizes Kustomize/Helm for customizing Kubernetes resources, and employs imops for simplified deployment and management. It details the splitting of configuration files for basic services, middleware, and RPC services to enhance modularity and ease of management. Additionally, it proposes strategies for sensitive data encryption and secure access using Kubernetes Secrets and KMS services.

1. oepnim server

- **`openim-api`** -> **`openim-api.yml`**
- **`openim-cmdutils`** -> **`openim-cmdutils.yml`**
- **`openim-crontask`** -> **`openim-crontask.yml`**
- **`openim-msggateway`** -> **`openim-msggateway.yml`**
- **`openim-msgtransfer`** -> **`openim-msgtransfer.yml`**
- **`openim-push`** -> **`openim-push.yml`**
- **`openim-rpc-auth`** -> **`openim-rpc-auth.yml`**
- **`openim-rpc-conversation`** -> **`openim-rpc-conversation.yml`**
- **`openim-rpc-friend`** -> **`openim-rpc-friend.yml`**
- **`openim-rpc-group`** -> **`openim-rpc-group.yml`**
- **`openim-rpc-msg`** -> **`openim-rpc-msg.yml`**
- **`openim-rpc-third`** -> **`openim-rpc-third.yml`**
- **`openim-rpc-user`** -> **`openim-rpc-user.yml`**

2. Configure the middleware

There should be separate configuration files for each type of middleware (such as Zookeeper, MongoDB, Redis, Kafka, etc.).Doing so facilitates reuse and independent management of middleware configurations.
+ zookeeper-config.yaml
+ mongo-config.yaml
+ redis-config.yaml
+ kafka-config.yaml

Configuration files are parsed through viper
```go
func initConfig() {
    viper.SetConfigName("openim")
    viper.AddConfigPath("./config")
    viper.ReadInConfig()

    viper.SetConfigName("mysql-config")
    viper.MergeInConfig()

    viper.SetConfigName("redis-config")
    viper.MergeInConfig()

    viper.SetConfigName("kafka-config")
    viper.MergeInConfig()
}
```

3. Configure object storage

Since the object storage configuration includes multiple options (such as Minio, COS, OSS, etc.)
object-storage-config.yaml

4. gRPC Load Balancing and Dynamic Scaling

**Automatic Scaling:**

- Horizontal Pod Autoscaler (HPA)

**Load Balancing:**

> There are several scenarios for gRPC load balancing:
> 
- Client-side load balancing
- Proxy load balancing (sometimes referred to as server-side load balancing)

**Configuration File Reading Strategy:**

Switching from using the addr mode to a `host:port` format, which facilitates easy deployment and scheduling.

```go
rpc_servers:
  - host: 192.168.1.1
    port: 8080
  - host: 192.168.1.2
    port: 8080
  - host: 192.168.1.3
    port: 8080
```

**Providing Configuration for Each RPC Service Address:**

Currently, it is implemented as follows:

```go
//   registerIP: ''
	rpcTcpAddr := net.JoinHostPort(network.GetListenIP(config.Rpc.ListenIP), strconv.Itoa(rpcPort))
	listener, err := net.Listen(
		"tcp",
		rpcTcpAddr,  // --log-level: Log level (e.g., info, debug).
	)
```

Enable external access by providing an IP.

Adapt the previous config to change the port's IP address.

5. Environment Variables

Redefining and optimizing the system through environment variables.

The design of environment variables is crucial as it significantly impacts the system.

```go
    viper.SetEnvPrefix("OPENIM")
    viper.AutomaticEnv()

    if err := viper.ReadInConfig(); err != nil {
        fmt.Println("Can't read config:", err)
        os.Exit(1)
    }
```

Variables prefixed with `APP` will automatically override those in the config.

## Migration

This section will outline the necessary steps for existing OpenIM implementations to migrate to this new configuration design. It will include details on transitioning to separated configuration files, integrating with Kubernetes Secrets for sensitive data, and adopting imops for deployment.

## Drawbacks

The complexity of management may increase due to the more granular approach to configuration. Additionally, the initial setup and migration for existing systems could be challenging and time-consuming.

## Alternatives

An alternative approach could involve a more centralized configuration management system, potentially simplifying certain aspects of deployment and maintenance at the expense of flexibility and scalability.

## Prior Art

This design draws inspiration from existing practices in cloud-native application development, particularly those related to Kubernetes, microservices architecture, and secrets management (e.g., HashiCorp Vault).

## Unresolved Questions

- The extent to which this design will impact the current performance and deployment speed of OpenIM applications.
- How to effectively manage and monitor the security of sensitive configurations.

## Spec. Changes (OPTIONAL)

N/A

## History

+ [https://traveling-thistle-a0c.notion.site/OpenIM-49b744a990b74eda875738e90c270202?pvs=74](https://traveling-thistle-a0c.notion.site/OpenIM-49b744a990b74eda875738e90c270202?pvs=74)

**Comment by cubxxw** [comment]
### Task List

#### 1. Configuration File Splitting
- **Description**: Split the existing configuration file into multiple smaller files for more flexible management and maintenance of configurations.
- **Sub-tasks**:
  - [ ] Analyze the current structure and content of the configuration file.
  - [ ] Determine criteria for splitting (e.g., by service, functionality).
  - [ ] Implement the splitting of the configuration file.
  - [ ] Test to ensure the split configuration files work correctly.

#### 2. Environment Variable Optimization
- **Description**: Clean up and optimize the setting of environment variables, removing those no longer used to ensure clarity and security of configurations.
- **Sub-tasks**:
  - [ ] Review the current list of environment variables, marking those no longer in use.
  - [ ] Remove marked environment variables.
  - [ ] Update documentation listing all environment variables and their purposes.

#### 3. Code Adjustments and Modifications
- **Description**: Adjust related code to accommodate changes in configuration file splitting and environment variable optimization.
- **Sub-tasks**:
  - [ ] Update the configuration loading logic in the code based on the results of the configuration file splitting.
  - [ ] Update references and logic for handling environment variables.
  - [ ] Conduct unit testing for modified parts.

#### 4. `.env` Environment Variables Redesign
- **Description**: Redesign the `.env` file for Docker environments to support the new configuration and environment variable strategy.
- **Sub-tasks**:
  - [ ] Design the new structure for the `.env` file.
  - [ ] Implement and test the new environment variable loading logic.
  - [ ] Update Docker-related documentation.

#### 5. OpenIM Docker Design
- **Description**: Design and implement Docker containers and configurations for OpenIM, optimizing containerized deployment.
- **Sub-tasks**:
  - [ ] Review and optimize the existing Dockerfile.
  - [ ] Design Docker container structures suitable for split configuration files.
  - [ ] Write and test Docker Compose scripts.

#### 6. Source Code Deployment Script Optimization
- **Description**: Optimize the source code deployment script to support the new configuration strategy and simplify the deployment process.
- **Sub-tasks**:
  - [ ] Analyze and refactor the existing deployment script.
  - [ ] Implement a new script supporting configuration file splitting and automated deployment.
  - [ ] Test and verify the effectiveness of the script.

#### 7. Automation Design: Configuration Optimization and Improvement
- **Description**: Design and implement an automation system for managing and applying configuration changes.
- **Sub-tasks**:
  - [ ] Research available tools for configuration management and automation.
  - [ ] Design the automation process, including configuration changes, review, and deployment.
  - [ ] Implement and test the automation system.

#### 8. Kubernetes Configuration File Redesign
- **Description**: Redesign configuration files for the Kubernetes environment to accommodate split configurations and enhance configuration flexibility.
- **Sub-tasks**:
  - [ ] Analyze the current Kubernetes configuration files.
  - [ ] Design a new configuration file structure supporting configuration file splitting.
  - [ ] Implement and test the new configuration files.

#### 9. Documentation Rewrite and Organization
- **Description**: Rewrite and update documentation to reflect all changes, ensuring the documentation reflects the latest configuration and deployment methods.
- **Sub-tasks**:
  - [ ] Review existing documentation to identify parts that need updates.
